### ISSUE TITLE
Interest in making this an npm module?

### ISSUE THREAD

**Issue by yuvilio** [iambumblehead/domwh#2]
To make this work in browserify, I needed to add ```module.exports = domwh``` to the bottom domwh.js file. Is that a worthwhile use case to add/pull request?

**Comment by iambumblehead** [comment]
https://github.com/iambumblehead/domwh/blob/master/domwh.js
https://www.npmjs.com/package/domwh

I added module.exports

**Comment by yuvilio** [comment]
Just re-installed and tested with 

```javascript
var domwh = require('domwh')
domwh(document.body)
```

Lookin good!

**Comment by iambumblehead** [comment]
thank you yuvilio
